###################### Metricbeat Configuration Example #######################

# This file is an example configuration file highlighting only the most common
# options. The metricbeat.full.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/index.html

#==========================  Modules configuration ============================
nestbeat.modules:

#----------------------------- thermostat Module -----------------------------
- module: thermostat
  metricsets: ["status"]
  enabled: true
  # Collection period is intentionally set to 60s in order to conform to Nest API data rate limits. See more at: https://developers.nest.com/documentation/cloud/data-rate-limits
  period: 60s
  hosts: ["localhost"]
  # OAuth access token which has to be used in order to authenticate against Nest API. It will have a prefix of "Bearer": in Authorization http header.
  accessToken: aJWTToken
  # Base url of Nest API
  apiHost: https://developer-api.nest.com
  # Nest Thermostat unique identifier (hexadecimal)
  deviceID: daddadd


